export const experience = [
  {
    position: "Bachelor of Science in Computer Science and Biology",
    shortPosition: "B.S. CS & Bio",
    company: "Northeastern University",
    location: "Boston, MA",
    category: "Education",
    image: "/northeastern.png",
    date: "Sep 2021 - May 2025",
    linkText: "northeastern.edu",
    linkURL: "https://www.northeastern.edu/",
    bullets: [
      "GPA 3.97/4.0 (summa cum laude)",
      "Honors Distinction",
      "CS courses: Software Engineering, Algorithms and Data, Object-Oriented Design, Artificial Intelligence, Database Design, Foundations of Data Science, Accelerated Fundamentals of Computer Science I & II, Discrete Structures",
      "Biology courses: Biology Capstone, Organic Chemistry I & II, Biochemistry, Genetics, Bioinformatics",
    ],
    showMore: false,
  },
  {
    position: "Software Engineer",
    shortPosition: "SWE",
    company: "HubSpot",
    location: "Cambridge, MA",
    category: "Work Experience",
    image: "/hubspot.svg",
    date: "June 2025 - Present",
    linkText: "hubspot.com",
    linkURL: "https://www.hubspot.com/",
    bullets: ["Engineer on the Associations Backend team"],
    showMore: false,
  },
  {
    position: "Software Technical Lead",
    shortPosition: "Software TL",
    company: "Generate Product Development",
    location: "Boston, MA",
    category: "Campus Experience",
    image: "/generate_logo.jpeg",
    date: "Aug 2024 - April 2025",
    linkText: "generatenu.com",
    linkURL: "https://generatenu.com/",
    bullets: [
      "Lead 6 engineers in engineering a cross-platform music review app; plan and lead weekly sprints",
      "Conduct code reviews and provide mentorship, utilizing Go, TypeScript, React Native for feature development",
    ],
    showMore: false,
  },
  {
    position: "Editor-in-Chief",
    company: "NU Sci Magazine",
    location: "Boston, MA",
    category: "Campus Experience",
    image: "/nusci.png",
    date: "May 2024 - April 2025",
    linkText: "nuscimagazine.com",
    linkURL: "https://nuscimagazine.com/",
    bullets: [
      "Shaping the creative direction of Northeastern’s student-run science magazine through 4 print issues",
      "Leading a team of 17 editors and 50+ writers and coordinating issue production with the executive board",
      "Editing 60+ articles per semester, providing feedback to refine content, clarity, accuracy, and engagement",
      "Selecting and arranging articles to create 44-page print issues",
      "Writing articles on topics relating to ecology, biology, health, and technology",
    ],
    showMore: false,
  },
  {
    position: "Professional Development for Co-op TA",
    shortPosition: "Professional Development TA",
    company: "Khoury College",
    location: "Boston, MA",
    category: "Campus Experience",
    image: "/khoury.jpg",
    date: "Sep 2024 - April 2025",
    linkText: "catalog.northeastern.edu",
    linkURL: "https://catalog.northeastern.edu/course-descriptions/cs/",
    bullets: [
      "Offering tailored advice for 100+ computer science undergraduates taking CS1210 during their first co-op job search",
      "Conducted 50+ resume reviews and 25+ mock interviews, boosting student confidence and job readiness",
    ],
    showMore: false,
  },
  {
    position: "Software Engineering Co-op",
    shortPosition: "SWE Co-op",
    company: "HubSpot",
    location: "Cambridge, MA",
    category: "Work Experience",
    image: "/hubspot.svg",
    date: "Jan 2024 - May 2024",
    linkText: "hubspot.com",
    linkURL: "https://www.hubspot.com/",
    bullets: [
      "Developed cron-based script scheduling API using Java, Dropwizard, and MySQL for triggering SQL scripts",
      "Built React interface using TypeScript and implemented scope-based gating to protect sensitive data",
      "Maintained ETL ingestion jobs using internal APIs, S3 buckets, & Snowflake for high-volume business intelligence needs",
    ],
    // TODO: remove showMore?
    showMore: false,
  },
  {
    position: "Software Developer",
    company: "Generate",
    location: "Boston, MA",
    category: "Campus Experience",
    image: "/generate.svg",
    date: "Mar 2023 - April 2024",
    linkText: "generatenu.com",
    linkURL: "https://generatenu.com/",
    bullets: [
      "Collaborated with developers and designers to build a gift recommendation platform for a real-world client",
      "Implemented Figma mockups using React, TypeScript, and Tailwind, creating an aesthetic, intuitive UI",
      "Assisted with architecting database schema, built and tested endpoints in Go for managing user and gift data",
    ],
    showMore: false,
  },

  {
    position: "Software Development Co-op",
    company: "Blueport",
    location: "Boston, MA",
    category: "Work Experience",
    image: "/blueport.png",
    date: "Jan 2023 - Dec 2023",
    linkText: "blueport.com",
    linkURL: "https://www.blueport.com/",
    bullets: [
      "Implemented and tested microservice endpoints in C# and Go to power e-commerce sites",
      "Developed 30+ procedures and tables in SQL Server and Postgres for efficient data management",
      "Spearheaded the company's tooling initiative by launching Retool development",
      "Developed 9 internal and client-facing Retool applications using SQL and JavaScript",
      "Documented tool development processes, gave demos, and offered support to other developers",
    ],
    showMore: false,
    details: null,
  },
  {
    position: "Software Developer",
    company: "Code4Community",
    location: "Boston, MA",
    category: "Campus Experience",
    image: "/c4c.png",
    date: "Mar 2023 - Dec 2023",
    linkText: "c4cneu.com",
    linkURL: "https://www.c4cneu.com/",
    bullets: [
      "Developed code for a letter of recommendation web application for the Abdul Latif Jameel Poverty Action Lab",
      "Completed tickets, participated in code reviews, and collaborated with project managers and designers",
    ],
    showMore: false,
  },
  {
    position: "Discrete Structures TA",
    company: "Khoury College",
    location: "Boston, MA",
    category: "Campus Experience",
    image: "/khoury.jpg",
    date: "Aug 2022 - Dec 2022",
    linkText: "CS 1800 Course Page",
    linkURL: "https://course.ccs.neu.edu/cs1800f22/",
    bullets: [
      "Hosted 4+ office hours weekly, answered student questions, and explained topics in discrete mathematics",
      "Graded homework assignments and exams, provided encouraging feedback for improvement",
    ],
    showMore: false,
  },
  {
    position: "Volunteer Teacher",
    company: "Boston EcoScholars",
    location: "Boston, MA",
    category: "Campus Experience",
    image: "/ecoscholars.png",
    date: "Jan 2022 - May 2022",
    linkText: "Boston EcoScholars",
    linkURL: "https://neu.campuslabs.com/engage/organization/ecoscholars",
    bullets: [
      "Prepared interactive lessons on environmental science and climate change for K-5 students",
      "Taught these lessons to after-school classes of up to 15 students in the greater Boston area",
      "Anticipated the needs of students to resolve conflicts and challenges and foster effective learning",
    ],
    showMore: false,
  },
];
